name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate .env file
        run: |
          echo "TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}" >> .env
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "MONGO_CONNECTION=${{ secrets.MONGO_CONNECTION }}" >> .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
          echo "FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}" >> .env
          echo "FACEBOOK_APP_SECRET=${{ secrets.FACEBOOK_APP_SECRET }}" >> .env
          echo "FACEBOOK_CALLBACK_URL=${{ secrets.FACEBOOK_CALLBACK_URL }}" >> .env
          echo "APPLE_CLIENT_ID=${{ secrets.APPLE_CLIENT_ID }}" >> .env
          echo "APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}" >> .env
          echo "APPLE_KEY_ID=${{ secrets.APPLE_KEY_ID }}" >> .env
          echo "APPLE_CALLBACK_URL=${{ secrets.APPLE_CALLBACK_URL }}" >> .env
          echo "CLIENT_URL_SUCCESS=${{ secrets.CLIENT_URL_SUCCESS }}" >> .env
          echo "CLIENT_URL_FAILURE=${{ secrets.CLIENT_URL_FAILURE }}" >> .env
          echo "CALLBACK_URL=${{ secrets.CALLBACK_URL }}" >> .env
          echo "apiKey=${{ secrets.apiKey }}" >> .env
          echo "authDomain=${{ secrets.authDomain }}" >> .env
          echo "projectId=${{ secrets.projectId }}" >> .env
          echo "storageBucket=${{ secrets.storageBucket }}" >> .env
          echo "messagingSenderId=${{ secrets.messagingSenderId }}" >> .env
          echo "appId=${{ secrets.appId }}" >> .env
          echo "measurementId=${{ secrets.measurementId }}" >> .env
          echo "MAIL_API_KEY=${{ secrets.MAIL_API_KEY }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "Email_Link=${{ secrets.Email_Link }}" >> .env
          
  

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude 'client' --exclude 'client' --exclude 'folders' 
          path: .
          remote_path: /home/ubuntu/SocialsBackend
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USERNAME }}
          remote_key: ${{ secrets.SERVER_PRIVATE_KEY }}


      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |            
            pm2 restart server
